### Register a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "example@example.com",
  "pass": "yourpassword"
}

###

### Login with user
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "example@example.com",
  "pass": "yourpassword"
}

###

### updateDiscountedItems
GET http://localhost:3000/api/item/update-discounted-items HTTP/1.1

### Track an item with ID XYZ
POST http://localhost:3000/api/user/track/650c41d9bc94be2217f8fb14
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTBiNjMwYmY4MzExOTg3NTVkNDdjNWIiLCJ1c2VybmFtZSI6ImV4YW1wbGVAZXhhbXBsZS5jb20iLCJpYXQiOjE2OTUzMDM0NDgsImV4cCI6MTY5NTMwNzA0OH0.Thu3JmAFQAH1lUVQVVLU7e1dpJl8BxfPjncyEs_gbBI

### Untrack an item with ID XYZ
DELETE http://localhost:3000/api/user/untrack/650c41d9bc94be2217f8fb14
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTBiNjMwYmY4MzExOTg3NTVkNDdjNWIiLCJ1c2VybmFtZSI6ImV4YW1wbGVAZXhhbXBsZS5jb20iLCJpYXQiOjE2OTUzMDM0NDgsImV4cCI6MTY5NTMwNzA0OH0.Thu3JmAFQAH1lUVQVVLU7e1dpJl8BxfPjncyEs_gbBI
