export const STORES = [
  {
    id: 223,
    store_id: '429',
    name: 'IKEA  Bydgoszcz',
    email: null,
    timezone: 'Europe/Warsaw',
    open_hour: 10,
    close_hour: 20,
    reserved_hours: 24,
    numberOfOffers: 208,
    items: null,
    country_code: 'pl',
  },
  {
    id: 194,
    store_id: '203',
    name: 'IKEA Gdańsk',
    email: null,
    timezone: 'Europe/Warsaw',
    open_hour: 9,
    close_hour: 21,
    reserved_hours: 24,
    numberOfOffers: 179,
    items: null,
    country_code: 'pl',
  },
  {
    id: 196,
    store_id: '306',
    name: 'IKEA Katowice',
    email: null,
    timezone: 'Europe/Warsaw',
    open_hour: 9,
    close_hour: 21,
    reserved_hours: 24,
    numberOfOffers: 159,
    items: null,
    country_code: 'pl',
  },
  {
    id: 218,
    store_id: '204',
    name: 'IKEA Kraków',
    email: null,
    timezone: 'Europe/Warsaw',
    open_hour: 9,
    close_hour: 21,
    reserved_hours: 24,
    numberOfOffers: 307,
    items: null,
    country_code: 'pl',
  },
  {
    id: 220,
    store_id: '311',
    name: 'IKEA Lublin',
    email: null,
    timezone: 'Europe/Warsaw',
    open_hour: 10,
    close_hour: 21,
    reserved_hours: 24,
    numberOfOffers: 222,
    items: null,
    country_code: 'pl',
  },
  {
    id: 219,
    store_id: '205',
    name: 'IKEA Poznań',
    email: null,
    timezone: 'Europe/Warsaw',
    open_hour: 9,
    close_hour: 21,
    reserved_hours: 24,
    numberOfOffers: 207,
    items: null,
    country_code: 'pl',
  },
  {
    id: 224,
    store_id: '583',
    name: 'IKEA Szczecin',
    email: null,
    timezone: 'Europe/Warsaw',
    open_hour: 10,
    close_hour: 20,
    reserved_hours: 24,
    numberOfOffers: 112,
    items: null,
    country_code: 'pl',
  },
  {
    id: 200,
    store_id: '188',
    name: 'IKEA Warszawa Janki',
    email: null,
    timezone: 'Europe/Warsaw',
    open_hour: 9,
    close_hour: 22,
    reserved_hours: 24,
    numberOfOffers: 206,
    items: null,
    country_code: 'pl',
  },
  {
    id: 221,
    store_id: '307',
    name: 'IKEA Warszawa Targówek',
    email: null,
    timezone: 'Europe/Warsaw',
    open_hour: 9,
    close_hour: 22,
    reserved_hours: 24,
    numberOfOffers: 251,
    items: null,
    country_code: 'pl',
  },
  {
    id: 199,
    store_id: '294',
    name: 'IKEA Wrocław',
    email: null,
    timezone: 'Europe/Warsaw',
    open_hour: 9,
    close_hour: 21,
    reserved_hours: 24,
    numberOfOffers: 283,
    items: null,
    country_code: 'pl',
  },
  {
    id: 222,
    store_id: '329',
    name: 'IKEA Łódź',
    email: null,
    timezone: 'Europe/Warsaw',
    open_hour: 10,
    close_hour: 21,
    reserved_hours: 24,
    numberOfOffers: 213,
    items: null,
    country_code: 'pl',
  },
];
